### ISSUE TITLE
Done step with link to the area with the note

### ISSUE THREAD

**Issue by sabas** [sabas/suosm#7]
In last screen link to corresponding area and tell to activate the notes layer.

**Comment by sabas** [comment]
And ask if they want to add another note, clearing all the data before going to first panel

**Comment by marcobra** [comment]
After inserting a note using this tool after pushing the "Done" button the address value must be set to an empty value. This to avoid to the user the ability to add multiple note value on exactly same point (the just inserted point).
The user can go back into page and changing the address for example adding a housenumber to the same address create two notes on the same point.     

Thanks

**Comment by sabas** [comment]
Fixed I think

**Comment by marcobra** [comment]
Sabas 

Still same issue here, i can easily insert same note on the same coordinate, without any kind of lock control, i think is not fixed...

**Comment by sabas** [comment]
See #8
